# CatBoost

- Comes from a combination of "Category" and "Boosting".
- Cat:
    - Works well with multiple categories of data: audio, text, images, etc
- Open source ML library fro Yandex.
- Integrates with deep learning frameworks like Google's TensorFlow and Apple's Core ML.
- Helps solve a wide range of business problems.
- Provides best-in-class accuracy.
- Power:
    - Provides out-of-the-box support for descriptive data formats.
    - Produces state-of-the-art results without extensive data training typically required by ML.
- Boost:
    - Based on gradient boosting library.
    - Gradient Boosting:
        - Powerful ML algorithm.
        - Widely applied to business: fraud detection, recommendation items, forecasting, predictions, classifier, etc.
        - Can return very good results with relatively less data unlike deep learning models that need a lot of data.

### What is Gradient Boosting?
- ML technique for regression and classification problems.
- Result:
    - Prediction model in the form of an ensemble weak prediction models. 
    - Typically made of decision trees.
- Decision Tree Model
    - Series of Yes/No rules based on features to match all possible outcomes of a decision.
- Decision Tree
    - Tree shaped diagram.
    - Determines a course of action, category.
    - Each branch represents a possible decision, occurence, or reaction.
    - Pros:
        - Easy to understand.
    - Cons:
        - Too simple
        - Not powerful enough for complex data
        - Not often used on its own for prediction
- Random Forest:
    - Takes advantage of many decision trees.
    - Rules created from subsamples of features.
    - Each tree is weaker than a full decision tree.
    - Combining trees produces better overall performance.
    - Pros:
        - Wisdom of the crowd
        - Results in high quality models
        - Fast to train
    - Cons:
        - Model can get huge
        - Hard to understand predictions
- Gradient Boosting Model
    - Uses even weaker decision trees.
    - Increasingly focused on hard examples.
    - Pros:
        - High performing
    - Cons:
        - Small change in feature set or training set can radically change model.
        - Hard to understand predictions.
- Gradient Boosting
    - Boostimg method
    - Ensemble learning technique
    - Combines models
- Summary:
    - Combines the predictions from 10s, 100s, or even 1000s of tree models.
    - Iteratively learns from weak learners to build a strong model.
    - Optimizes regression, classification, and ranking.

---

### Load Data

#### Question: Whether We Should Buy or Sell Crypto

In [4]:
#!pip install yfinance

In [5]:
import yfinance

symbol = "XRP-USD"

start = "2014-01-01"

end = "2021-01-01"

dataframe = yfinance.download(symbol, start, end)

dataframe

[*********************100%***********************]  1 of 1 completed

Price          Close      High       Low      Open       Volume
Ticker       XRP-USD   XRP-USD   XRP-USD   XRP-USD      XRP-USD
Date
2017-11-09  0.217488  0.221791  0.214866  0.217911    147916992
2017-11-10  0.206483  0.219068  0.205260  0.218256    141032992
2017-11-11  0.210430  0.214456  0.205459  0.205948    134503008
2017-11-12  0.197339  0.210214  0.195389  0.210214    251175008
2017-11-13  0.203442  0.204081  0.197456  0.197472    132567000
...              ...       ...       ...       ...          ...
2020-12-27  0.283039  0.307464  0.270248  0.294758   9250325478
2020-12-28  0.247958  0.306016  0.239413  0.283366   8389871765
2020-12-29  0.220962  0.248318  0.174831  0.247673  12970077098
2020-12-30  0.211828  0.235360  0.194670  0.220902   8894036560
2020-12-31  0.219846  0.227613  0.206465  0.211787   5363979601

[1149 rows x 5 columns]

In [6]:
dataframe.to_csv("xrp_2014_2021.csv")

---

### Process Data

In [8]:
#Create a column that can be used for classification: wheter buy or sell crypto
import numpy as np

BUY = 1

SELL = 0

dataframe["Buy/Sell"] = np.where(dataframe["Close"].shift(-1) > dataframe["Close"],
                                BUY,
                                SELL)

dataframe

Price          Close      High       Low      Open       Volume Buy/Sell
Ticker       XRP-USD   XRP-USD   XRP-USD   XRP-USD      XRP-USD
Date
2017-11-09  0.217488  0.221791  0.214866  0.217911    147916992        0
2017-11-10  0.206483  0.219068  0.205260  0.218256    141032992        1
2017-11-11  0.210430  0.214456  0.205459  0.205948    134503008        0
2017-11-12  0.197339  0.210214  0.195389  0.210214    251175008        1
2017-11-13  0.203442  0.204081  0.197456  0.197472    132567000        1
...              ...       ...       ...       ...          ...      ...
2020-12-27  0.283039  0.307464  0.270248  0.294758   9250325478        0
2020-12-28  0.247958  0.306016  0.239413  0.283366   8389871765        0
2020-12-29  0.220962  0.248318  0.174831  0.247673  12970077098        0
2020-12-30  0.211828  0.235360  0.194670  0.220902   8894036560        1
2020-12-31  0.219846  0.227613  0.206465  0.211787   5363979601        0

[1149 rows x 6 columns]

In [11]:
# Define y and X
y = dataframe["Buy/Sell"].values

y

array([0, 1, 0, ..., 0, 1, 0])

In [13]:
X = dataframe[["High", "Low", "Close", "Volume"]].values

X

array([[2.21790999e-01, 2.14865997e-01, 2.17488006e-01, 1.47916992e+08],
       [2.19068006e-01, 2.05259994e-01, 2.06483006e-01, 1.41032992e+08],
       [2.14456007e-01, 2.05458999e-01, 2.10429996e-01, 1.34503008e+08],
       ...,
       [2.48318002e-01, 1.74831003e-01, 2.20962003e-01, 1.29700771e+10],
       [2.35359997e-01, 1.94670007e-01, 2.11827993e-01, 8.89403656e+09],
       [2.27613002e-01, 2.06465006e-01, 2.19845995e-01, 5.36397960e+09]])

In [16]:
#Split data into training and testing
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

X_train.shape

(919, 4)

In [17]:
X_test.shape

(230, 4)

In [19]:
y_train.shape

(919,)

In [20]:
y_test.shape

(230,)

In [21]:
#Build CatBoost Classifier Model
#!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-win_amd64.whl.metadata (1.5 kB)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in c:\users\dnmun\anaconda3\lib\site-packages (from catboost) (3.9.2)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\users\dnmun\anaconda3\lib\site-packages (from catboost) (1.26.4)
Requirement already satisfied: pandas<4.0,>=0.24 in c:\users\dnmun\anaconda3\lib\site-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in c:\users\dnmun\anaconda3\lib\site-packages (from catboost) (1.13.1)
Requirement already satisfied: plotly in c:\users\dnmun\anaconda3\lib\site-packages (from catboost) (5.24.1)
Requirement already satisfied: six in c:\users\dnmun\anaconda3\lib\site-packages (from catboost) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dnmun\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dnmun\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dnmun\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2023.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dnmun\anaconda3\lib\site-packages (from matplotlib->catboost) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\dnmun\anaconda3\lib\site-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dnmun\anaconda3\lib\site-packages (from matplotlib->catboost) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dnmun\anaconda3\lib\site-packages (from matplotlib->catboost) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\dnmun\anaconda3\lib\site-packages (from matplotlib->catboost) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\dnmun\anaconda3\lib\site-packages (from matplotlib->catboost) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\dnmun\anaconda3\lib\site-packages (from matplotlib->catboost) (3.1.2)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\dnmun\anaconda3\lib\site-packages (from plotly->catboost) (8.2.3)
Downloading catboost-1.2.10-cp312-cp312-win_amd64.whl (100.2 MB)
   ---------------------------------------- 0.0/100.2 MB ? eta -:--:--
   -- ------------------------------------- 6.6/100.2 MB 36.6 MB/s eta 0:00:03
   ----- ---------------------------------- 14.2/100.2 MB 35.6 MB/s eta 0:00:03
   -------- ------------------------------- 21.8/100.2 MB 35.3 MB/s eta 0:00:03
   ----------- ---------------------------- 29.6/100.2 MB 36.2 MB/s eta 0:00:02
   -------------- ------------------------- 37.0/100.2 MB 36.2 MB/s eta 0:00:02
   ------------------ --------------------- 45.4/100.2 MB 36.5 MB/s eta 0:00:02
   --------------------- ------------------ 53.7/100.2 MB 37.2 MB/s eta 0:00:02
   ------------------------- -------------- 63.7/100.2 MB 38.3 MB/s eta 0:00:01
   ---------------------------- ----------- 72.4/100.2 MB 38.4 MB/s eta 0:00:01
   --------------------------------- ------ 83.1/100.2 MB 39.9 MB/s eta 0:00:01
   ------------------------------------ --- 92.3/100.2 MB 40.3 MB/s eta 0:00:01
   --------------------------------------  100.1/100.2 MB 40.7 MB/s eta 0:00:01
   --------------------------------------- 100.2/100.2 MB 38.1 MB/s eta 0:00:00
Downloading graphviz-0.21-py3-none-any.whl (47 kB)
Installing collected packages: graphviz, catboost

   ---------------------------------------- 0/2 [graphviz]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   ---------------------------------------- 2/2 [catboost]

Successfully installed catboost-1.2.10 graphviz-0.21

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [23]:
import catboost

from catboost import CatBoostClassifier

model = CatBoostClassifier(iterations = 10, learning_rate = 0.1)

model.fit(X_train, y_train)

model.is_fitted()

0:	learn: 0.6915688	total: 140ms	remaining: 1.26s
1:	learn: 0.6902294	total: 141ms	remaining: 564ms
2:	learn: 0.6890465	total: 142ms	remaining: 331ms
3:	learn: 0.6878330	total: 142ms	remaining: 214ms
4:	learn: 0.6868772	total: 143ms	remaining: 143ms
5:	learn: 0.6853140	total: 144ms	remaining: 96ms
6:	learn: 0.6842932	total: 145ms	remaining: 62ms
7:	learn: 0.6835469	total: 146ms	remaining: 36.4ms
8:	learn: 0.6823929	total: 146ms	remaining: 16.2ms
9:	learn: 0.6815378	total: 147ms	remaining: 0us

True

In [24]:
models_predictions = model.predict(X_test)

models_predictions

array([0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1], dtype=int64)

In [25]:
#Accuracy
model.score(X_test, y_test)

0.5565217391304348